### ISSUE TITLE
点击“reload config"时，出错。

### ISSUE THREAD

**Issue by luckypoem** [HoonHwang/SpechtLiteConf#3]
hi.

我只修改了Conf.yaml文件中的adapter3部分的host,port,method,password的值如下：

 - id: adapter3
    type: ss
    host: my_vps_ip
    port: 8989
    # Currently support: AES-128-CFB, AES-192-CFB, AES-256-CFB, chacha20, salsa20, rc4-md5
    # Shadowsocks encryption methods are not fully tested, please report if there is anything not working.
    method: AES-256-CFB
    password: my_pw

不过点击“reload config"时，弹出窗口，提示：
"error when parsing config file:/users/xyz/.spechtlite/Conf.yaml.
InvalidYamlFile"

怎么解决？
谢谢你

**Comment by HoonHwang** [comment]
你没把adapter1，2删掉？

**Comment by luckypoem** [comment]
hi.
我把把adapter1，2删掉了，还是出现同样的错误提示。难道要把adapter4那一部分也删除？

**Comment by HoonHwang** [comment]
嗯，不需要的adapter都需要删掉

**Comment by luckypoem** [comment]
现在可以了。但是不稳定。感觉远不如shadowsocksX好用

**Comment by HoonHwang** [comment]
没有啊，用着很稳定的。
有不稳定的情况或者其他疑问，欢迎进到官方Telegram群跟SpechtLite的作者提问哦~
[![Join the chat at https://telegram.me/NEKitGroup](https://img.shields.io/badge/chat-on%20Telegram-blue.svg)](https://telegram.me/NEKitGroup)

**Comment by luckypoem** [comment]
hi.
mac下，只是搭配safari才好用。不过即使如此，在访问非https网站时，还是打不开。比如http://artab.blog9.fc2.com ， http://xajh.blog132.fc2.com ，如何解决？

**Comment by HoonHwang** [comment]
把SPEED类型里的direct部分删掉，然后delay改成0，再试试
如：
- id: proxy
    type: SPEED
    adapters:
      - id: adapter1
        delay: 0
      - id: adapter2
        delay: 0
      - id: adapter3
        delay: 0

**Comment by luckypoem** [comment]
哈。还真的可以了。
非常感谢！！
