### ISSUE TITLE
多服務器配置只能建立多配置文件嗎？

### ISSUE THREAD

**Issue by ky0ncheng** [HoonHwang/SpechtLiteConf#4]
![](https://github.com/zhuhaow/SpechtLite/raw/master/imgs/screenshot.png)

可不可以多服務器配置寫在同一個配置文件中？

**Comment by HoonHwang** [comment]
可以啊，一个adapter对应一个服务器
你这个截图是多个配置文件

**Comment by ky0ncheng** [comment]
懂了 感謝解答！
