### ISSUE TITLE
可否配置域名呢？

### ISSUE THREAD

**Issue by gaotong2055** [HoonHwang/SpechtLiteConf#5]
类似pac那种，对一些域名进行代理

**Comment by HoonHwang** [comment]
这个conf文件是一个模版，所以代理列表里是空的。
但因为conf文件里的rule里对GEOIP进行了判断，所以目前的规则是国内走直连，国外走代理。
如果需要指定某个网站走代理，可以按需求在proxylist文件里按正则表达式写入。
如：github\.com 就会匹配所有github.com的链接
proxyiprange文件里写入需要指定翻墙的ip地址。
