### ISSUE TITLE
多个SS服务器配置问题？

### ISSUE THREAD

**Issue by wanghaixiang** [HoonHwang/SpechtLiteConf#7]
如何在一个配置文件里配置多个SS服务器配置呢？

**Comment by ChengLuffy** [comment]
`Conf.yaml` 里 `adapter1 adapter2 adapter3 adapter4` 都只是举例，你可以任意更改增加删除，增加的 `SS` 服务器配置，`type` 为 `ss`，其他不用的应当删除。
但是要注意的是 `id :proxy` 下节点名称应与上方节点名称相对应，如 `id :proxy` 下没有加入上面的节点，SpechtLite 将不会使用该节点。

**Comment by wanghaixiang** [comment]
感谢回复，原来我直接添加了adapter，没有与id:proxy下的名称对应，所以一直提示出错。现在已经成功添加了

在 2016年10月20日 上午9:54，ChengLuffy <notifications@github.com>写道：
